//..................................................... Header
// Project: MatchingBalls
//    Path: C:\PalmDev\PilotMAG\My Projects\MatchingBalls\MatchingBalls.ppp
//    Date: 29/09/2002  22:31:20
// Include File automatically generated by PilotMAG
//
// NEXT ID: 1073

//..................................................... Program
#define IconID 1001
#define VersionID 1
#define ApplicationID 1002

//..................................................... Fonts
//..................................................... Strings
//..................................................... Alerts
#define altDebug 1017
#define altGameState 1020
#define altHighScores 1031
#define altConfirm 1058

//..................................................... Menus
#define mnuNew 1022
#define mnuGame 1023
#define mnuShowScores 1035
#define mnuAbout 1024
#define mnuHelp 1025
#define mnuHighScores 1032
#define mnuUndo 1036
#define mnuClearLowScores 1037
#define mnuClearAllScores 1038
#define mnuSendHighScores 1039
#define mnuNewTwoPlayer 1059
#define mnuGameBreakdown 1060
#define mnuPlayGameSeed 1061
#define mnuReplayLastGame 1069
#define mnuGameOptions 1070
#define mnuViewGameSeed 1072

//..................................................... Bitmaps
#define bmp0 1006
#define bmp1 1007
#define bmp2 1008
#define bmp3 1009
#define bmp4 1010
#define bmp5 1011
#define bmp6 1012
#define bmp7 1013
#define bmp8 1014
#define bmp9 1015
#define bmpDead 1016
#define bmpMask 1018
#define bmpRestart 1057

//..................................................... Forms
#define frmMain 1004
#define frmGameResults 1021

#define gdtScore 1034

#define btnOK 1026
#define Label1008 1027
#define Label1009 1028
#define Label1010 1029
#define Label1011 1030

//..................................................... Categories

//.................................................... String Table
#define InstructionsStr 1019
#define strAbout 1033
//............................................................. Hex

//............................................................ Data

#define frmGameOptions 1062
#define btnOptOk 1063
#define chkDblTap 1064
#define chkSound 1065
#define chkAutoClear 1066
#define chkTimeout 1071